### PR TITLE
fixed navbar issue

### PR DESCRIPTION
**Pull request by GAGANRAGHAV**
i have fixed the navbar issue in different screens and light and dark mode and some issue in navbar in contact page

image

### CODE REVIEW

**Comment by Anupkjha2601** [comment]
@GAGANRAGHAV there is conflict you have to add login and signup page please resolve this conflict .

**Comment by GAGANRAGHAV** [comment]
Okay sir

**Comment by GAGANRAGHAV** [comment]
sir i have resolved the merge conflict.. please merge the pr

**Comment by GAGANRAGHAV** [comment]
Sir please merge the pr the issue is fixed

**Pull request merged**
